version: '2'

services:
  aio: &aio
    build:
      context: .
      dockerfile: ./compose/aio/Dockerfile
    image: recipes_local_aio
    depends_on:
      - postgres
    env_file:
      - ./.env/.aio
      - ./.env/.postgres
    ports:
      - "8000:8080"
    volumes:
      - ./uploads:/uploads
    environment:
      DEBUG: 'true'
    command: /start

  postgres:
    image: postgres:latest
    env_file:
      - ./.env/.postgres
    ports:
      - "5431:5432"

  redis:
    image: redis:3.2

  swagger:
    build:
      context: .
      dockerfile: ./compose/swagger/Dockerfile
    ports:
      - "8001:8080"
    image: recipes_local_swagger
    env_file:
      - ./.env/.swagger